[package]
name = "crcc"
version = "0.1.0"
edition = "2024"

[lib]
name = "crcc"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "native_benchmark"
path = "src/bin/native_benchmark.rs"
required-features = ["benchmarking"]

[[bin]]
name = "parallel_benchmark"
path = "src/bin/parallel_benchmark.rs"
required-features = ["rayon"]

[features]
default = ["parry", "rhusics", "collide"]
parry = ["dep:parry2d-f64"]
rhusics = ["dep:cgmath", "dep:collision", "dep:rhusics-core"]
collide = [
    "dep:collide",
    "dep:collide-convex",
    "dep:collide-sphere",
    "dep:simple-vectors",
]
python_bindings = ["dep:pyo3", "rayon"]
rayon = ["dep:rayon"]
benchmarking = []

[dependencies]
derive_more = { version = "2.1.1", features = [
    "add",
    "mul",
    "sum",
    "display",
    "error",
    "from",
] }
enum_dispatch = "0.3.13"
geo = "0.32.0"
glamx = { version = "0.1.3", features = ["approx"] }
itertools = "0.14.0"
parry2d-f64 = { version = "0.26.0", optional = true }
rhusics-core = { version = "0.7.0", optional = true }
pyo3 = { version = "0.27.1", features = ["abi3-py310"], optional = true }
rayon = { version = "1.11.0", optional = true }
replace_with = "0.1.8"
cgmath = { version = "0.16.0", optional = true }
collision = { version = "0.18.0", optional = true }
collide = { version = "0.7.0", optional = true }
collide-convex = { version = "0.5.3", features = ["sphere"], optional = true }
collide-sphere = { version = "0.3.1", optional = true }
simple-vectors = { version = "0.5.0", optional = true }

[dev-dependencies]
rstest = "0.26.1"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
# DENY PANICS:
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
