[package]
name = "commonroad-collision-checker"
version = "0.1.0"
edition = "2024"

[lib]
name = "commonroad_collision_checker"
crate-type = ["cdylib", "rlib"]

[features]
python_bindings = ["dep:pyo3"]

[dependencies]
derive_more = { version = "2.1.1", features = ["add", "mul", "sum"] }
enum_dispatch = "0.3.13"
geo = "0.32.0"
itertools = "0.14.0"
nalgebra = "0.34.1"
parry2d-f64 = "0.25.3"
pyo3 = { version = "0.27.1", features = ["abi3-py310"], optional = true }
rayon = "1.11.0"
replace_with = "0.1.8"
