[package]
name = "commonroad-collision-checker"
version = "0.1.0"
edition = "2024"

[lib]
name = "commonroad_collision_checker"
crate-type = ["cdylib", "rlib"]

[dependencies]
geo = "0.32.0"
nalgebra = "0.34.1"
parry2d-f64 = "0.25.3"
pyo3 = { version = "0.27.1", features = ["extension-module"] }
rayon = "1.11.0"
