[project]
name = "commonroad-collision-checker"
version = "0.1.0"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
authors = [
    { name = "Cyber-Physical Systems Group - Technical University of Munich", email = "commonroad@lists.lrz.de" },
]
description = ""
keywords = []
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: POSIX :: Linux",
]
dependencies = ["commonroad-io>=2023.1"]

[dependency-groups]
dev = ["pre-commit>=2.21.0", "ruff==0.14.8"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "commonroad_collision_checker._core"
python-packages = ["commonroad_collision_checker"]
python-source = "src"

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "rust/Cargo.toml" },
    { file = "**/*.rs" },
]

[tool.ruff]
line-length = 120
indent-width = 4
format.quote-style = "double"
target-version = "py310"
lint.ignore = ["E203"]
lint.select = ["E4", "E7", "E9", "F", "I"]
