from __future__ import annotations

from typing import Tuple

class Pose:
    def __init__(self, translation: Tuple[float, float], angle: float) -> None: ...
    @staticmethod
    def identity() -> Pose: ...
    @staticmethod
    def translation(translation: Tuple[float, float]) -> Pose: ...
    @staticmethod
    def rotation(angle: float) -> Pose: ...
    def and_then(self, other: Pose) -> Pose: ...

__all__ = ["Pose"]
