from __future__ import annotations

from typing import Tuple

class Pose:
    def __init__(self, translation: Tuple[float, float], angle: float) -> None: ...
    @staticmethod
    def identity() -> Pose: ...
    @staticmethod
    def from_translation(translation: Tuple[float, float]) -> Pose: ...
    @staticmethod
    def from_rotation(angle: float) -> Pose: ...
    @property
    def translation(self) -> Tuple[float, float]: ...
    @property
    def rotation(self) -> float: ...
    def and_then(self, other: Pose) -> Pose: ...

__all__ = ["Pose"]
