from __future__ import annotations

from typing import Tuple

from crcc._core.pose import Pose as _Pose

__all__ = ["Pose"]

class Pose(_Pose):
    def __init__(self, translation: Tuple[float, float], angle: float) -> None: ...
    @staticmethod
    def identity() -> Pose: ...
    @staticmethod
    def from_translation(translation: Tuple[float, float]) -> Pose: ...
    @staticmethod
    def from_rotation(angle: float) -> Pose: ...
    @property
    def translation(self) -> Tuple[float, float]: ...
    @property
    def rotation(self) -> float: ...
    def compose(self, other: Pose) -> Pose: ...
    def __mul__(self, other: Pose) -> Pose: ...
