stages:
  - static-check
  - build-and-test
  - build-wheels
  - deploy

default:
  image: python:3.12-slim-bookworm
  before_script:
    - apt-get update && apt-get install -y git curl build-essential
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=stable --profile=minimal -y
    - source "$HOME/.cargo/env"

.python-version-unprotected-branches: &python-version-unprotected-branches "3.10"

.python-versions: &python-versions
  - *python-version-unprotected-branches
  - "3.11"
  - "3.12"
  - "3.13"

pre_commit:
  stage: static-check
  script:
    - rustup component add rustfmt
    - rustup component add clippy
    - pip install pre-commit
    - pre-commit run --all-files --show-diff-on-failure

build-rust:
  stage: build-and-test
  script:
    - cargo build
    - cargo test
  needs: [ ]

build-sdist:
  stage: build-wheels
  script:
    - pip install uv
    - uv build --sdist
  needs: [ ]
  artifacts:
    paths:
      - dist/*.tar.gz
    expire_in: 30 minutes


.common-rules:
  rules:
    # Rule to disable a job for merge request pipelines (imitate default job behaviour)
    - &skip_merge_request_pipeline
      if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - &skip_scheduled_pipeline
      if: $CI_PIPELINE_SOURCE == "schedule"
      when: never

build-wheel:
  stage: build-wheels
  image: quay.io/pypa/manylinux_2_28:2025.12.07-1
  variables:
    PYTHON_VERSION: *python-version-unprotected-branches
  script:
    - uv build --python $PYTHON_VERSION --wheel dist/*.tar.gz
    - auditwheel repair -w wheelhouse dist/*.whl
  needs:
    - job: build-sdist
      artifacts: true
  artifacts:
    paths:
      - wheelhouse/*.whl
    expire_in: 30 minutes
  rules:
    - *skip_merge_request_pipeline
    # Only run this on the unprotected branches, for protected branches we use cibuildwheel with docker-in-docker
    - if: $CI_COMMIT_REF_PROTECTED == "false"

build-wheel-cibw:
  stage: build-wheels
  # Use the privileged runner as required for Docker-in-Docker (dind)
  tags:
    - dind
  image: $CI_REGISTRY/tum-cps/commonroad-docker/wheelenv:2025.2
  before_script: [ ]
  # make a docker daemon available for cibuildwheel to use
  services:
    - name: docker:20.10-dind
      entrypoint: [ "env", "-u", "DOCKER_HOST" ]
      command: [ "dockerd-entrypoint.sh" ]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
    # We only use the artifacts (sdist/wheels) from previous jobs, so skip all Git operations
    GIT_STRATEGY: none
  script:
    - pipx run 'cibuildwheel == 3.*' dist/*.tar.gz
  needs:
    - job: build-sdist
      artifacts: true
  artifacts:
    paths:
      - wheelhouse/*.whl
    expire_in: 30 minutes
  rules:
    # We only run the docker-in-docker job on protected branches
    - if: $CI_COMMIT_REF_PROTECTED == "false"
      when: never
    - *skip_merge_request_pipeline
    - when: on_success

upload-wheel-internal:
  stage: deploy
  before_script:
    - pip install uv
  variables:
    UV_PUBLISH_USERNAME: gitlab-ci-token
    UV_PUBLISH_PASSWORD: ${CI_JOB_TOKEN}
    UV_PUBLISH_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    # We only use the artifacts (sdist/wheels) from previous jobs, so skip all Git operations
    GIT_STRATEGY: none
  script:
    - uv publish dist/*.tar.gz wheelhouse/*.whl
  needs:
    - job: build-sdist
      artifacts: true
    - job: build-wheel
      artifacts: true
      optional: true
    - job: build-wheel-cibw
      artifacts: true
      optional: true
  rules:
    # Disable job for merge request pipelines (imitate default job behaviour)
    - *skip_merge_request_pipeline
    - *skip_scheduled_pipeline
    - if: $CI_COMMIT_BRANCH == "development"
      when: manual
